/* empty css                      */import{S as d,i}from"./assets/vendor-BrddEoy-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const p="46829470-2665f0a199f61e35def0ecb3b",y="https://pixabay.com/api/";async function h(s){const o=new URLSearchParams({key:p,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"});try{const r=await fetch(`${y}?${o.toString()}`);if(!r.ok)throw new Error("Network response was not ok");return await r.json()}catch(r){throw r}}const l=document.querySelector(".gallery");function g(s){const o=s.map(({webformatURL:n,largeImageURL:e,tags:t,likes:a,views:f,comments:u,downloads:m})=>`
      <a href="${e}" class="gallery__item">
        <img src="${n}" alt="${t}" loading="lazy" />
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${a}</p>
          <p class="info-item"><b>Views:</b> ${f}</p>
          <p class="info-item"><b>Comments:</b> ${u}</p>
          <p class="info-item"><b>Downloads:</b> ${m}</p>
        </div>
      </a>`).join("");l.insertAdjacentHTML("beforeend",o),new d(".gallery a").refresh()}const b=document.getElementById("form"),c=document.querySelector(".loader");b.addEventListener("submit",async s=>{s.preventDefault(),l.innerHTML="";const o=s.target.elements.searchquery.value.trim();if(o===""){i.error({title:"Error",message:"Please enter a search query"});return}c.style.display="block";try{const r=await h(o);c.style.display="none",r.hits.length===0?i.info({message:"Sorry, there are no images matching your search query. Please try again!"}):g(r.hits)}catch(r){c.style.display="none",i.error({title:"Error",message:r.message})}});
//# sourceMappingURL=index.js.map
